FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

#Installe TOUTES les dépendances (y compris devDependencies)
RUN npm install

COPY . .
RUN npm run build
CMD ["node", "dist/index.js"]


#Commande console

##cd tp2-app

# Builder l'image naïve
##

# Mesurer la taille
##docker images tp2-naive:v1

# Notez la taille : 202 MB